groups:
- name: alert.rules
  rules:
  - alert: InstanceDown
    # Condition for alerting
    expr: up == 0
    # Duration for which the condition should be true before firing the alert
    for: 1m
    # Annotation - additional informational labels to store more information
    annotations:
      title: 'Instance {{ $labels.instance }} down'
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute.'
    # Labels - additional labels to be attached to the alert
    labels:
        severity: 'critical'

  - alert: HostOutOfMemory
    # Condition for alerting
    expr: node_memory_free_bytes / node_memory_total_bytes * 100 < 25
    # Duration for which the condition should be true before firing the alert
    for: 5m
    # Annotation - additional informational labels to store more information
    annotations:
      title: 'Host out of memory (instance {{ $labels.instance }})'
      description: 'Node memory is filling up (< 25% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}'
    # Labels - additional labels to be attached to the alert
    labels:
        severity: 'warning'

  # Uncomment and configure the following rule for high CPU load alert
  # - alert: HostHighCpuLoad
  #   # Condition for alerting
  #   expr: (sum by (instance) (irate(node_cpu{job="node_exporter_metrics",mode="idle"}[5m]))) > 80
  #   # Duration for which the condition should be true before firing the alert
  #   for: 5m
  #   # Annotation - additional informational labels to store more information
  #   annotations:
  #     title: 'Host high CPU load (instance {{ $labels.instance }})'
  #     description: 'CPU load is > 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}'
  #   # Labels - additional labels to be attached to the alert
  #   labels:
  #       severity: 'warning'

  - alert: HostOutOfDiskSpace
    # Condition for alerting
    expr: (node_filesystem_avail_bytes{mountpoint="/"}  * 100) / node_filesystem_size_bytes{mountpoint="/"} < 50
    # Duration for which the condition should be true before firing the alert
    for: 5m
    # Annotation - additional informational labels to store more information
    annotations:
      title: 'Host out of disk space (instance {{ $labels.instance }})'
      description: 'Disk is almost full (< 50% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}'
    # Labels - additional labels to be attached to the alert
    labels:
        severity: 'warning' 
groups:
- name: alert.rules
  rules:
  - alert: InstanceDown
    # Condition for alerting
    expr: up == 0
    # Duration for which the condition should be true before firing the alert
    for: 1m
    # Annotation - additional informational labels to store more information
    annotations:
      title: 'Instance {{ $labels.instance }} down'
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute.'
    # Labels - additional labels to be attached to the alert
    labels:
        severity: 'critical'

  - alert: HostOutOfMemory
    # Condition for alerting
    expr: node_memory_free_bytes / node_memory_total_bytes * 100 < 25
    # Duration for which the condition should be true before firing the alert
    for: 5m
    # Annotation - additional informational labels to store more information
    annotations:
      title: 'Host out of memory (instance {{ $labels.instance }})'
      description: 'Node memory is filling up (< 25% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}'
    # Labels - additional labels to be attached to the alert
    labels:
        severity: 'warning'

  # Uncomment and configure the following rule for high CPU load alert
  # - alert: HostHighCpuLoad
  #   # Condition for alerting
  #   expr: (sum by (instance) (irate(node_cpu{job="node_exporter_metrics",mode="idle"}[5m]))) > 80
  #   # Duration for which the condition should be true before firing the alert
  #   for: 5m
  #   # Annotation - additional informational labels to store more information
  #   annotations:
  #     title: 'Host high CPU load (instance {{ $labels.instance }})'
  #     description: 'CPU load is > 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}'
  #   # Labels - additional labels to be attached to the alert
  #   labels:
  #       severity: 'warning'

  - alert: HostOutOfDiskSpace
    # Condition for alerting
    expr: (node_filesystem_avail_bytes{mountpoint="/"}  * 100) / node_filesystem_size_bytes{mountpoint="/"} < 50
    # Duration for which the condition should be true before firing the alert
    for: 5m
    # Annotation - additional informational labels to store more information
    annotations:
      title: 'Host out of disk space (instance {{ $labels.instance }})'
      description: 'Disk is almost full (< 50% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}'
    # Labels - additional labels to be attached to the alert
    labels:
        severity: 'warning' 
