global:
  # Set the interval at which Prometheus will scrape targets
  scrape_interval: 15s
  # Set the interval at which Prometheus will evaluate rules
  evaluation_interval: 15s

scrape_configs:
  # Job to discover and scrape exporters
  - job_name: 'Exporters'
    file_sd_configs:
      - files:
          # Specify the file that contains the list of targets to scrape
          - /path_to_your_targets-file/targets.yml
        # How often Prometheus checks the file for changes
        refresh_interval: 30s

# Additional scrape configurations can be defined here

# Uncomment and modify the below sections if you want to create specific scrape jobs for node_exporter or wmi_exporter

# scrape_configs:
#   - job_name: 'node_exporter'
#     file_sd_configs:
#       - files:
#           - /path_to_your_targets-file/targets.yml
#         refresh_interval: 30s
    # Optional: Define metric_relabel_configs or other configurations specific to node_exporter job

#   - job_name: 'wmi_exporter'
#     file_sd_configs:
#       - files:
#           - /path_to_your_targets-file/targets.yml
#         refresh_interval: 30s
    # Optional: Define metric_relabel_configs or other configurations specific to wmi_exporter job

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        # Specify the address of the Alertmanager to send alerts to
        - 'localhost:9093'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'
rule_files:
  # Specify the file that contains alert rules
  - "alert_rules.yml"
