global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'Exporters'
    file_sd_configs:
      - files:
          - /opt/homebrew/etc/targets.yml
        refresh_interval: 30s
        #
#scrape_configs:
#  - job_name: 'node_exporter'
#    file_sd_configs:
#      - files:
#          - /opt/homebrew/etc/targets.yml
#        refresh_interval: 30s
    # Optional: Define metric_relabel_configs or other configurations specific to node_exporter job

#  - job_name: 'wmi_exporter'
#    file_sd_configs:
#      - files:
#          - /opt/homebrew/etc/targets.yml
#        refresh_interval: 30s
    # Optional: Define metric_relabel_configs or other configurations specific to wmi_exporter job

# Additional scrape_configs for other jobs as needed

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - 'localhost:9093'
# Load rules once and periodically evaluate them according to the global 'evaluation interval'
rule_files:
  - "alert_rules.yml"
#scrape_configs:
#
#  - job_name: "prometheus"
#    static_configs:
#    - targets: ["localhost:9090"]
#
#  - job_name: "My_node"
#    static_configs:
#    - targets: ["localhost:9100"]
#
#  - job_name: "Aditya_node"
#    static_configs:
#    - targets: ["192.168.20.220:9100"]
#
#  - job_name: "Mukund_node"
#    static_configs:
#    - targets: ["192.168.20.210:9182"]
#
#  - job_name: "Yash_node"
#    static_configs:
#    - targets: ["192.168.20.222:9182"]
#
#  - job_name: "Monal_node"
#    static_configs:
#    - targets: ["192.168.20.116:9182"]